---
type: pipeline
name: Build Reeve Step "Node Get Package Version"

when:
  workerGroup:
    include: [soldier]
  trigger:
    include: [commit, action]
  file:
    include:
      - config.env
      - .reeve.yaml
  action:
    include: [reeveci:steps:node-get-package-version:build]

steps:
  - name: Load env
    task: "@reeve/load-env-file"
    params:
      FILES: config.env
      LOAD_ALL: "true"

  - name: Build image
    task: "@docker/build"
    params:
      DOCKER_LOGIN_REGISTRIES: { env: docker/hub/login }
      NAME: docker.io/reeveci/step-node-get-package-version
      TAG: { var: STEP_VERSION }
      PLATFORM: amd64
